# Covid-19 Deaths Registered Weekly

Data downloaded from [weeklyprovisionalfiguresondeathsregisteredinenglandandwales](https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/weeklyprovisionalfiguresondeathsregisteredinenglandandwales)

In [193]:
import pandas as pd
pd.options.mode.chained_assignment = None

### Load data

In [239]:
df = pd.read_excel('../../data/publishedweek512020corrected.xlsx',
                   sheet_name='Weekly figures 2020',
                   header=5,
                   skipfooter=13)

df = df.drop(df.columns[-2:], axis=1)

In [240]:
df.head()

,Week ended,Unnamed: 1,2020-01-03 00:00:00,2020-01-10 00:00:00,2020-01-17 00:00:00,2020-01-24 00:00:00,2020-01-31 00:00:00,2020-02-07 00:00:00,2020-02-14 00:00:00,2020-02-21 00:00:00,...,2020-10-16 00:00:00,2020-10-23 00:00:00,2020-10-30 00:00:00,2020-11-06 00:00:00,2020-11-13 00:00:00,2020-11-20 00:00:00,2020-11-27 00:00:00,2020-12-04 00:00:00,2020-12-11 00:00:00,2020-12-18 00:00:00
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Total deaths, all ages",NaN,12254.0,14058.0,12990.0,11856.0,11612.0,10986.0,10944.0,10841.0,...,10534.0,10739.0,10887.0,11812.0,12254.0,12535.0,12456.0,12303.0,12292.0,13011.0
3,Total deaths: average of corresponding,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,week over the previous 5 years 1 (England and ...,NaN,12175.0,13822.0,13216.0,12760.0,12206.0,11925.0,11627.0,11548.0,...,9865.0,9759.0,9891.0,10331.0,10350.0,10380.0,10357.0,10695.0,10750.0,11548.0

In [241]:
df.tail()

,Week ended,Unnamed: 1,2020-01-03 00:00:00,2020-01-10 00:00:00,2020-01-17 00:00:00,2020-01-24 00:00:00,2020-01-31 00:00:00,2020-02-07 00:00:00,2020-02-14 00:00:00,2020-02-21 00:00:00,...,2020-10-16 00:00:00,2020-10-23 00:00:00,2020-10-30 00:00:00,2020-11-06 00:00:00,2020-11-13 00:00:00,2020-11-20 00:00:00,2020-11-27 00:00:00,2020-12-04 00:00:00,2020-12-11 00:00:00,2020-12-18 00:00:00
85,E12000006,East,1162.0,1573.0,1457.0,1410.0,1286.0,1259.0,1172.0,1167.0,...,1056.0,1154.0,1089.0,1177.0,1172.0,1186.0,1159.0,1229.0,1224.0,1317.0
86,E12000007,London,1113.0,1272.0,1073.0,1028.0,1092.0,987.0,967.0,1032.0,...,923.0,922.0,888.0,952.0,1112.0,1086.0,1012.0,1029.0,1065.0,1167.0
87,E12000008,South East,1814.0,2132.0,2064.0,1833.0,1820.0,1729.0,1688.0,1675.0,...,1462.0,1510.0,1563.0,1614.0,1616.0,1687.0,1655.0,1720.0,1706.0,1947.0
88,E12000009,South West,1225.0,1487.0,1466.0,1253.0,1233.0,1157.0,1169.0,1118.0,...,1174.0,1044.0,1129.0,1174.0,1168.0,1159.0,1272.0,1284.0,1156.0,1311.0
89,W92000004,Wales,787.0,939.0,767.0,723.0,727.0,690.0,728.0,679.0,...,688.0,661.0,712.0,832.0,742.0,848.0,797.0,836.0,814.0,882.0

I'll start by tidying the dates up. We don't need the time.

In [242]:
for i in df.columns[2:]:
    df.rename(columns={i: pd.datetime.date(i)}, inplace=True)

In [243]:
df.head(10)

,Week ended,Unnamed: 1,2020-01-03,2020-01-10,2020-01-17,2020-01-24,2020-01-31,2020-02-07,2020-02-14,2020-02-21,...,2020-10-16,2020-10-23,2020-10-30,2020-11-06,2020-11-13,2020-11-20,2020-11-27,2020-12-04,2020-12-11,2020-12-18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Total deaths, all ages",NaN,12254.0,14058.0,12990.0,11856.0,11612.0,10986.0,10944.0,10841.0,...,10534.0,10739.0,10887.0,11812.0,12254.0,12535.0,12456.0,12303.0,12292.0,13011.0
3,Total deaths: average of corresponding,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,week over the previous 5 years 1 (England and ...,NaN,12175.0,13822.0,13216.0,12760.0,12206.0,11925.0,11627.0,11548.0,...,9865.0,9759.0,9891.0,10331.0,10350.0,10380.0,10357.0,10695.0,10750.0,11548.0
5,Total deaths: average of corresponding,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,week over the previous 5 years 1 (England),NaN,11412.0,12933.0,12370.0,11933.0,11419.0,11154.0,10876.0,10790.0,...,9215.0,9104.0,9248.0,9675.0,9662.0,9701.0,9690.0,9995.0,10034.0,10804.0
7,Total deaths: average of corresponding,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,week over the previous 5 years 1 (Wales),NaN,756.0,856.0,812.0,802.0,760.0,729.0,722.0,724.0,...,630.0,628.0,616.0,625.0,658.0,653.0,646.0,679.0,693.0,718.0
9,Note: Deaths could possibly be counted in both...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [244]:
df_sum = df.iloc[:13]
df_sum.rename(columns={'Week ended': 'Summary'}, inplace=True)
df_sum['Summary'][11] = df_sum['Unnamed: 1'][11]
df_sum['Summary'][12] = df_sum['Unnamed: 1'][12]
df_sum.set_index('Summary', inplace=True)
df_sum.drop(columns=['Unnamed: 1'], inplace=True)
df_sum.dropna(axis=0, how='all', inplace=True)
df_sum

,2020-01-03,2020-01-10,2020-01-17,2020-01-24,2020-01-31,2020-02-07,2020-02-14,2020-02-21,2020-02-28,2020-03-06,...,2020-10-16,2020-10-23,2020-10-30,2020-11-06,2020-11-13,2020-11-20,2020-11-27,2020-12-04,2020-12-11,2020-12-18
Summary,,,,,,,,,,,,,,,,,,,,,
"Total deaths, all ages",12254.0,14058.0,12990.0,11856.0,11612.0,10986.0,10944.0,10841.0,10816.0,10895.0,...,10534.0,10739.0,10887.0,11812.0,12254.0,12535.0,12456.0,12303.0,12292.0,13011.0
week over the previous 5 years 1 (England and Wales),12175.0,13822.0,13216.0,12760.0,12206.0,11925.0,11627.0,11548.0,11183.0,11498.0,...,9865.0,9759.0,9891.0,10331.0,10350.0,10380.0,10357.0,10695.0,10750.0,11548.0
week over the previous 5 years 1 (England),11412.0,12933.0,12370.0,11933.0,11419.0,11154.0,10876.0,10790.0,10448.0,10745.0,...,9215.0,9104.0,9248.0,9675.0,9662.0,9701.0,9690.0,9995.0,10034.0,10804.0
week over the previous 5 years 1 (Wales),756.0,856.0,812.0,802.0,760.0,729.0,722.0,724.0,698.0,720.0,...,630.0,628.0,616.0,625.0,658.0,653.0,646.0,679.0,693.0,718.0
Deaths where the underlying cause was respiratory disease (ICD-10 J00-J99),2140.0,2476.0,2189.0,1893.0,1746.0,1572.0,1602.0,1619.0,1547.0,1583.0,...,1032.0,996.0,1019.0,1029.0,1007.0,944.0,925.0,891.0,962.0,984.0
Deaths where COVID-19 was mentioned on the death certificate (ICD-10 U07.1 and U07.2),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,670.0,978.0,1379.0,1937.0,2466.0,2697.0,3040.0,2835.0,2756.0,2986.0

In [245]:
df_reg = df.iloc[80:]
df_reg.rename(columns={'Unnamed: 1': 'Region'}, inplace=True)
df_reg.set_index('Region', inplace=True)
df_reg.drop(columns='Week ended', inplace=True)

df_reg

,2020-01-03,2020-01-10,2020-01-17,2020-01-24,2020-01-31,2020-02-07,2020-02-14,2020-02-21,2020-02-28,2020-03-06,...,2020-10-16,2020-10-23,2020-10-30,2020-11-06,2020-11-13,2020-11-20,2020-11-27,2020-12-04,2020-12-11,2020-12-18
Region,,,,,,,,,,,,,,,,,,,,,
North East,673.0,707.0,647.0,612.0,561.0,564.0,573.0,539.0,572.0,568.0,...,606.0,600.0,591.0,675.0,711.0,691.0,679.0,645.0,661.0,689.0
North West,1806.0,1932.0,1696.0,1529.0,1461.0,1529.0,1427.0,1477.0,1476.0,1490.0,...,1553.0,1714.0,1754.0,1900.0,1950.0,1935.0,1791.0,1679.0,1691.0,1718.0
Yorkshire and The Humber,1240.0,1339.0,1278.0,1187.0,1136.0,1072.0,1059.0,1087.0,1078.0,1112.0,...,1001.0,1111.0,1168.0,1294.0,1350.0,1441.0,1501.0,1403.0,1326.0,1380.0
East Midlands,1060.0,1195.0,1106.0,1024.0,1015.0,922.0,976.0,924.0,919.0,930.0,...,904.0,891.0,882.0,990.0,1099.0,1105.0,1218.0,1121.0,1199.0,1199.0
West Midlands,1349.0,1450.0,1407.0,1231.0,1262.0,1052.0,1159.0,1116.0,1174.0,1098.0,...,1154.0,1124.0,1102.0,1186.0,1317.0,1385.0,1358.0,1340.0,1432.0,1385.0
East,1162.0,1573.0,1457.0,1410.0,1286.0,1259.0,1172.0,1167.0,1115.0,1149.0,...,1056.0,1154.0,1089.0,1177.0,1172.0,1186.0,1159.0,1229.0,1224.0,1317.0
London,1113.0,1272.0,1073.0,1028.0,1092.0,987.0,967.0,1032.0,1085.0,982.0,...,923.0,922.0,888.0,952.0,1112.0,1086.0,1012.0,1029.0,1065.0,1167.0
South East,1814.0,2132.0,2064.0,1833.0,1820.0,1729.0,1688.0,1675.0,1587.0,1726.0,...,1462.0,1510.0,1563.0,1614.0,1616.0,1687.0,1655.0,1720.0,1706.0,1947.0
South West,1225.0,1487.0,1466.0,1253.0,1233.0,1157.0,1169.0,1118.0,1133.0,1170.0,...,1174.0,1044.0,1129.0,1174.0,1168.0,1159.0,1272.0,1284.0,1156.0,1311.0
Wales,787.0,939.0,767.0,723.0,727.0,690.0,728.0,679.0,651.0,652.0,...,688.0,661.0,712.0,832.0,742.0,848.0,797.0,836.0,814.0,882.0

In [271]:
df_age = df.iloc[15:79]
df_age.drop(columns='Week ended', inplace=True)
df_age.drop([df_age.index[20], df_age.index[21], df_age.index[42], df_age.index[43]], inplace=True)

sex = (['Persons']*len(df_age['Unnamed: 1'].unique()) +
       ['Males']*len(df_age['Unnamed: 1'].unique()) +
       ['Females']*len(df_age['Unnamed: 1'].unique()))

index = list(zip(*[sex, df_age['Unnamed: 1']]))
index = pd.MultiIndex.from_tuples(tuple(zip(sex, df_age['Unnamed: 1'])), names=["Sex", "Age"])

df_age.drop(columns='Unnamed: 1', inplace=True)

df_age.set_index(index, inplace=True)



df_age

#df_age.rename(columns={'Unnamed: 1': 'Age'}, inplace=True)
#df_age.drop(columns='Week ended', inplace=True)
#df_age.set_index('Age', inplace=True)
#df_age

               2020-01-03  2020-01-10  2020-01-17  2020-01-24  2020-01-31  \
Sex     Age
Persons <1           48.0        50.0        69.0        53.0        50.0
        1-4           8.0         9.0         7.0         9.0         6.0
        5-9           4.0         8.0         5.0         4.0         5.0
        10-14         4.0         9.0         4.0         8.0         4.0
        15-19         6.0        16.0        10.0        15.0        23.0
        20-24        11.0        23.0        25.0        30.0        23.0
        25-29        17.0        37.0        37.0        36.0        28.0
        30-34        32.0        46.0        47.0        38.0        58.0
        35-39        54.0        68.0        77.0        79.0        76.0
        40-44        69.0        85.0       118.0       116.0       100.0
        45-49       115.0       191.0       189.0       160.0       163.0
        50-54       239.0       279.0       306.0       280.0       278.0
        55-59       361.0       426.0       461.0       381.0       382.0
        60-64       486.0       604.0       562.0       535.0       525.0
        65-69       696.0       857.0       803.0       791.0       732.0
        70-74      1164.0      1341.0      1210.0      1167.0      1196.0
        75-79      1535.0      1724.0      1612.0      1474.0      1445.0
        80-84      2049.0      2290.0      2103.0      1863.0      1811.0
        85-89      2457.0      2697.0      2421.0      2188.0      2124.0
        90+        2898.0      3297.0      2924.0      2626.0      2583.0
Males   <1           30.0        29.0        38.0        28.0        22.0
        1-4           5.0         4.0         4.0         6.0         4.0
        5-9           2.0         4.0         4.0         4.0         4.0
        10-14         1.0         7.0         3.0         4.0         3.0
        15-19         5.0         8.0         5.0        14.0        17.0
        20-24         7.0        14.0        21.0        23.0        16.0
        25-29         7.0        28.0        31.0        31.0        19.0
        30-34        21.0        28.0        29.0        22.0        40.0
        35-39        32.0        46.0        49.0        45.0        45.0
        40-44        43.0        52.0        72.0        79.0        58.0
        45-49        62.0       114.0       106.0        90.0       107.0
        50-54       137.0       156.0       200.0       181.0       180.0
        55-59       191.0       259.0       295.0       215.0       247.0
        60-64       275.0       355.0       338.0       334.0       324.0
        65-69       415.0       509.0       471.0       482.0       437.0
        70-74       697.0       761.0       690.0       663.0       683.0
        75-79       826.0       924.0       886.0       819.0       827.0
        80-84      1053.0      1172.0      1080.0       951.0       919.0
        85-89      1098.0      1231.0      1117.0      1014.0       970.0
        90+         982.0      1127.0       991.0       910.0       872.0
Females <1           18.0        21.0        31.0        25.0        28.0
        1-4           3.0         5.0         3.0         3.0         2.0
        5-9           2.0         4.0         1.0         0.0         1.0
        10-14         3.0         2.0         1.0         4.0         1.0
        15-19         1.0         8.0         5.0         1.0         6.0
        20-24         4.0         9.0         4.0         7.0         7.0
        25-29        10.0         9.0         6.0         5.0         9.0
        30-34        11.0        18.0        18.0        16.0        18.0
        35-39        22.0        22.0        28.0        34.0        31.0
        40-44        26.0        33.0        46.0        37.0        42.0
        45-49        53.0        77.0        83.0        70.0        56.0
        50-54       102.0       123.0       106.0        99.0        98.0
        55-59       170.0       167.0       166.0       166.0       135.0
        60-64       211.0       249.0       224.0       201.0       201.0
        65-69       281.0       348.0       332.0       309.0       295.0
        70-74       467.0       580.0       520.0       504.0       513.0
        75-79       709.0       800.0       726.0       655.0       618.0
        80-84       996.0      1118.0      1023.0       912.0       892.0
        85-89      1359.0      1466.0      1304.0      1174.0      1154.0
        90+        1916.0      2170.0      1933.0      1716.0      1711.0

               2020-02-07  2020-02-14  2020-02-21  2020-02-28  2020-03-06  \
Sex     Age
Persons <1           30.0        43.0        51.0        49.0        56.0
        1-4           8.0         6.0         5.0         7.0        11.0
        5-9           4.0         2.0         6.0         6.0         2.0
        10-14         4.0         4.0         7.0         7.0         7.0
        15-19        10.0        16.0        20.0        24.0        21.0
        20-24        34.0        26.0        18.0        25.0        23.0
        25-29        23.0        27.0        29.0        28.0        39.0
        30-34        38.0        40.0        60.0        50.0        53.0
        35-39        71.0        85.0        77.0        85.0        72.0
        40-44        95.0        92.0       117.0       103.0       104.0
        45-49       157.0       165.0       182.0       155.0       155.0
        50-54       289.0       288.0       232.0       261.0       258.0
        55-59       371.0       345.0       346.0       347.0       358.0
        60-64       512.0       490.0       511.0       494.0       481.0
        65-69       689.0       641.0       695.0       682.0       679.0
        70-74      1120.0      1113.0      1048.0      1111.0      1090.0
        75-79      1358.0      1305.0      1338.0      1255.0      1325.0
        80-84      1698.0      1704.0      1696.0      1713.0      1798.0
        85-89      2040.0      2039.0      1927.0      2015.0      1969.0
        90+        2433.0      2517.0      2475.0      2398.0      2391.0
Males   <1           14.0        29.0        32.0        30.0        31.0
        1-4           5.0         4.0         5.0         6.0         7.0
        5-9           2.0         1.0         4.0         4.0         1.0
        10-14         4.0         3.0         2.0         5.0         2.0
        15-19         8.0         9.0        14.0        16.0        13.0
        20-24        23.0        19.0        14.0        19.0        16.0
        25-29        11.0        19.0        17.0        21.0        27.0
        30-34        24.0        27.0        39.0        32.0        33.0
        35-39        53.0        52.0        46.0        51.0        45.0
        40-44        55.0        58.0        72.0        64.0        69.0
        45-49        95.0        99.0       105.0        95.0        93.0
        50-54       175.0       172.0       140.0       147.0       153.0
        55-59       208.0       209.0       195.0       189.0       220.0
        60-64       306.0       287.0       285.0       286.0       278.0
        65-69       423.0       400.0       400.0       417.0       388.0
        70-74       626.0       660.0       598.0       647.0       646.0
        75-79       713.0       726.0       778.0       709.0       725.0
        80-84       875.0       870.0       894.0       871.0       938.0
        85-89       943.0       995.0       906.0       956.0       932.0
        90+         843.0       852.0       893.0       870.0       841.0
Females <1           16.0        14.0        19.0        19.0        25.0
        1-4           3.0         2.0         0.0         1.0         4.0
        5-9           2.0         1.0         2.0         2.0         1.0
        10-14         0.0         1.0         5.0         2.0         5.0
        15-19         2.0         7.0         6.0         8.0         8.0
        20-24        11.0         7.0         4.0         6.0         7.0
        25-29        12.0         8.0        12.0         7.0        12.0
        30-34        14.0        13.0        21.0        18.0        20.0
        35-39        18.0        33.0        31.0        34.0        27.0
        40-44        40.0        34.0        45.0        39.0        35.0
        45-49        62.0        66.0        77.0        60.0        62.0
        50-54       114.0       116.0        92.0       114.0       105.0
        55-59       163.0       136.0       151.0       158.0       138.0
        60-64       206.0       203.0       226.0       208.0       203.0
        65-69       266.0       241.0       295.0       265.0       291.0
        70-74       494.0       453.0       450.0       464.0       444.0
        75-79       645.0       579.0       560.0       546.0       600.0
        80-84       823.0       834.0       802.0       842.0       860.0
        85-89      1097.0      1044.0      1021.0      1059.0      1037.0
        90+        1590.0      1665.0      1582.0      1528.0      1550.0

               ...  2020-10-16  2020-10-23  2020-10-30  2020-11-06  \
Sex     Age    ...
Persons <1     ...        41.0        34.0        31.0        43.0
        1-4    ...         6.0         2.0         6.0         6.0
        5-9    ...         4.0         7.0         2.0         2.0
        10-14  ...         3.0         5.0         5.0         4.0
        15-19  ...        15.0        14.0        15.0        12.0
        20-24  ...        17.0        22.0        23.0        20.0
        25-29  ...        28.0        33.0        39.0        35.0
        30-34  ...        67.0        51.0        48.0        47.0
        35-39  ...        73.0        86.0        96.0        85.0
        40-44  ...        96.0       121.0       102.0       127.0
        45-49  ...       165.0       174.0       160.0       155.0
        50-54  ...       267.0       260.0       271.0       267.0
        55-59  ...       364.0       401.0       411.0       402.0
        60-64  ...       535.0       495.0       513.0       560.0
        65-69  ...       625.0       680.0       709.0       741.0
        70-74  ...      1097.0      1156.0      1136.0      1230.0
        75-79  ...      1408.0      1376.0      1404.0      1519.0
        80-84  ...      1614.0      1746.0      1758.0      1983.0
        85-89  ...      1896.0      1878.0      1936.0      2061.0
        90+    ...      2213.0      2198.0      2222.0      2513.0
Males   <1     ...        20.0        22.0        17.0        27.0
        1-4    ...         5.0         2.0         3.0         4.0
        5-9    ...         3.0         5.0         2.0         0.0
        10-14  ...         3.0         1.0         3.0         2.0
        15-19  ...         8.0         6.0        10.0         7.0
        20-24  ...        14.0        15.0        20.0        15.0
        25-29  ...        18.0        21.0        30.0        22.0
        30-34  ...        44.0        36.0        29.0        29.0
        35-39  ...        47.0        56.0        60.0        56.0
        40-44  ...        60.0        70.0        67.0        77.0
        45-49  ...       109.0       110.0        98.0        88.0
        50-54  ...       143.0       152.0       178.0       162.0
        55-59  ...       227.0       251.0       250.0       240.0
        60-64  ...       310.0       299.0       301.0       353.0
        65-69  ...       364.0       370.0       414.0       439.0
        70-74  ...       610.0       676.0       681.0       717.0
        75-79  ...       783.0       752.0       767.0       845.0
        80-84  ...       826.0       904.0       893.0      1070.0
        85-89  ...       913.0       885.0       927.0       979.0
        90+    ...       761.0       777.0       813.0       889.0
Females <1     ...        21.0        12.0        14.0        16.0
        1-4    ...         1.0         0.0         3.0         2.0
        5-9    ...         1.0         2.0         0.0         2.0
        10-14  ...         0.0         4.0         2.0         2.0
        15-19  ...         7.0         8.0         5.0         5.0
        20-24  ...         3.0         7.0         3.0         5.0
        25-29  ...        10.0        12.0         9.0        13.0
        30-34  ...        23.0        15.0        19.0        18.0
        35-39  ...        26.0        30.0        36.0        29.0
        40-44  ...        36.0        51.0        35.0        50.0
        45-49  ...        56.0        64.0        62.0        67.0
        50-54  ...       124.0       108.0        93.0       105.0
        55-59  ...       137.0       150.0       161.0       162.0
        60-64  ...       225.0       196.0       212.0       207.0
        65-69  ...       261.0       310.0       295.0       302.0
        70-74  ...       487.0       480.0       455.0       513.0
        75-79  ...       625.0       624.0       637.0       674.0
        80-84  ...       788.0       842.0       865.0       913.0
        85-89  ...       983.0       993.0      1009.0      1082.0
        90+    ...      1452.0      1421.0      1409.0      1624.0

               2020-11-13  2020-11-20  2020-11-27  2020-12-04  2020-12-11  \
Sex     Age
Persons <1           45.0        54.0        44.0        50.0        45.0
        1-4           8.0        11.0         7.0         4.0         3.0
        5-9           7.0         6.0         5.0         3.0        11.0
        10-14         3.0         4.0         5.0         8.0         6.0
        15-19         7.0        17.0        18.0        15.0         8.0
        20-24        24.0        17.0        33.0        27.0        25.0
        25-29        41.0        39.0        41.0        42.0        35.0
        30-34        64.0        50.0        58.0        50.0        58.0
        35-39        76.0        83.0        99.0        88.0        69.0
        40-44       107.0       118.0       101.0       117.0       115.0
        45-49       173.0       179.0       207.0       200.0       190.0
        50-54       302.0       321.0       328.0       293.0       299.0
        55-59       432.0       412.0       416.0       468.0       433.0
        60-64       583.0       588.0       602.0       568.0       603.0
        65-69       739.0       788.0       757.0       792.0       765.0
        70-74      1277.0      1235.0      1242.0      1236.0      1230.0
        75-79      1570.0      1678.0      1562.0      1528.0      1619.0
        80-84      2082.0      2107.0      1999.0      1975.0      1989.0
        85-89      2224.0      2183.0      2289.0      2237.0      2193.0
        90+        2490.0      2645.0      2643.0      2602.0      2596.0
Males   <1           21.0        34.0        26.0        30.0        21.0
        1-4           2.0         6.0         2.0         3.0         2.0
        5-9           6.0         5.0         3.0         2.0         8.0
        10-14         2.0         3.0         4.0         4.0         2.0
        15-19         4.0        12.0        13.0         9.0         6.0
        20-24        16.0        14.0        27.0        14.0        19.0
        25-29        31.0        24.0        30.0        31.0        17.0
        30-34        45.0        34.0        39.0        30.0        35.0
        35-39        43.0        52.0        64.0        60.0        39.0
        40-44        60.0        61.0        54.0        75.0        74.0
        45-49       110.0       110.0       136.0       117.0       122.0
        50-54       173.0       203.0       191.0       178.0       188.0
        55-59       277.0       254.0       249.0       291.0       279.0
        60-64       340.0       372.0       374.0       352.0       381.0
        65-69       438.0       498.0       468.0       465.0       465.0
        70-74       797.0       738.0       762.0       715.0       741.0
        75-79       917.0       956.0       900.0       867.0       908.0
        80-84      1134.0      1140.0      1066.0      1062.0      1073.0
        85-89      1041.0      1044.0      1101.0      1073.0      1030.0
        90+         882.0       965.0       941.0       935.0       909.0
Females <1           24.0        20.0        18.0        20.0        24.0
        1-4           6.0         5.0         5.0         1.0         1.0
        5-9           1.0         1.0         2.0         1.0         3.0
        10-14         1.0         1.0         1.0         4.0         4.0
        15-19         3.0         5.0         5.0         6.0         2.0
        20-24         8.0         3.0         6.0        13.0         6.0
        25-29        10.0        15.0        11.0        11.0        18.0
        30-34        19.0        16.0        19.0        20.0        23.0
        35-39        33.0        31.0        35.0        28.0        30.0
        40-44        47.0        57.0        47.0        42.0        41.0
        45-49        63.0        69.0        71.0        83.0        68.0
        50-54       129.0       118.0       137.0       115.0       111.0
        55-59       155.0       158.0       167.0       177.0       154.0
        60-64       243.0       216.0       228.0       216.0       222.0
        65-69       301.0       290.0       289.0       327.0       300.0
        70-74       480.0       497.0       480.0       521.0       489.0
        75-79       653.0       722.0       662.0       661.0       711.0
        80-84       948.0       967.0       933.0       913.0       916.0
        85-89      1183.0      1139.0      1188.0      1164.0      1163.0
        90+        1608.0      1680.0      1702.0      1667.0      1687.0

               2020-12-18
Sex     Age
Persons <1           46.0
        1-4           5.0
        5-9           4.0
        10-14         5.0
        15-19        11.0
        20-24        24.0
        25-29        38.0
        30-34        57.0
        35-39        73.0
        40-44       115.0
        45-49       189.0
        50-54       317.0
        55-59       437.0
        60-64       581.0
        65-69       805.0
        70-74      1246.0
        75-79      1614.0
        80-84      2124.0
        85-89      2439.0
        90+        2881.0
Males   <1           25.0
        1-4           3.0
        5-9           3.0
        10-14         2.0
        15-19         5.0
        20-24        19.0
        25-29        28.0
        30-34        37.0
        35-39        48.0
        40-44        66.0
        45-49       118.0
        50-54       189.0
        55-59       271.0
        60-64       348.0
        65-69       477.0
        70-74       752.0
        75-79       895.0
        80-84      1120.0
        85-89      1185.0
        90+        1079.0
Females <1           21.0
        1-4           2.0
        5-9           1.0
        10-14         3.0
        15-19         6.0
        20-24         5.0
        25-29        10.0
        30-34        20.0
        35-39        25.0
        40-44        49.0
        45-49        71.0
        50-54       128.0
        55-59       166.0
        60-64       233.0
        65-69       328.0
        70-74       494.0
        75-79       719.0
        80-84      1004.0
        85-89      1254.0
        90+        1802.0

[60 rows x 51 columns]